name: $(GitVersion.MajorMinorPatch)-$(GitVersion.ShortSha)

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

stages:
  - stage: A
    displayName: "Build and Test"

    jobs:
      - job: build
        displayName: "Build and Test"

        steps:
          - task: gittools.gitversion.gitversion-task.GitVersion@5
            displayName: GitVersion

          - task: UseDotNet@2
            displayName: "Use .Net Core sdk 3.0.x"
            inputs:
              version: 3.0.x

          - task: DotNetCoreCLI@2
            displayName: "dotnet restore"
            inputs:
              command: restore
              projects: "**/*.sln"

          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              projects: "**/LetkaBike.sln"
              arguments: "--configuration $(BuildConfiguration) --no-restore"
              workingDirectory: src/LetkaBike/

          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: test
              projects: "**/*.Tests.csproj"
              workingDirectory: src/LetkaBike
