trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

stages:
  - stage: A
    displayName: "Build and Test"

    jobs:
      - job: build
        displayName: "Build and Test"

        steps:
          - task: gittools.gitversion.gitversion-task.GitVersion@5
            displayName: GitVersion

          - task: UseDotNet@2
            displayName: "Use .Net Core sdk 3.0.x"
            inputs:
              version: 3.0.x

          - task: DotNetCoreCLI@2
            displayName: "dotnet restore"
            inputs:
              command: restore
              projects: "**/*.sln"

          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              projects: "**/LetkaBike.sln"
              arguments: "--configuration $(BuildConfiguration) --no-restore"
              workingDirectory: src/LetkaBike/

          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: test
              projects: "**/*.Tests.csproj"
              workingDirectory: src/LetkaBike

          - task: DotNetCoreCLI@2
            displayName: "dotnet publish"
            inputs:
              command: publish
              arguments: "--configuration $(BuildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory) --verbosity d /p:Version=$(Build.BuildNumber)"
              modifyOutputPath: false
              workingDirectory: src/LetkaBike

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: drop"

  - stage: B
    displayName: "Deploy"

    jobs:
      - deployment: dev
        displayName: "Deploy to dev"

        pool:
          vmImage: "ubuntu-latest"

        environment: "letkabike-dev"

        strategy:
          runOnce:
            deploy:
              steps:
                - download: none

                - task: DownloadBuildArtifacts@0
                  inputs:
                    artifactName: "a.zip"
                    buildType: "current"
                    downloadType: "single"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: app-letkabike-dev-001"
                  inputs:
                    azureSubscription: "azure-letkabike-dev"
                    appType: webAppLinux
                    WebAppName: "app-letkabike-dev-001"
                    RuntimeStack: "DOTNETCORE|Latest"
                    StartupCommand: "dotnet LetkaBike.API.dll"
